import 'dart:convert';

class Ig0063 {
  Ig0063(
      {required this.codEmp,
      required this.clsSdv,
      required this.codVen,
      required this.numSdv,
      required this.fecSdv,
      required this.nunSdv,
      required this.frmSdv,
      required this.codRef,
      required this.codPto,
      required this.codMov,
      required this.numMov,
      required this.fecMov,
      required this.frmMov,
      required this.secMov,
      required this.codPro,
      required this.canB91,
      required this.canB92,
      required this.canB93,
      required this.canB94,
      required this.canB95,
      required this.canB96,
      required this.clsMdm,
      required this.codMdm,
      required this.obsMdm,
      required this.codMrm,
      required this.obsMrm,
      required this.ofsSdv,
      required this.obsSdv,
      required this.codCop,
      required this.nomCop,
      required this.ngrCop,
      required this.fgrCop,
      required this.bltCop,
      required this.destino,
      required this.ptoRel,
      required this.codRel,
      required this.numRel,
      required this.fecRel,
      required this.ptoNex,
      required this.codNex,
      required this.numNex,
      required this.fecNex,
      required this.swsSdv,
      required this.ucrSdv,
      required this.fcrSdv,
      required this.uacSdv,
      required this.facSdv,
      required this.uapSdv,
      required this.fapSdv,
      required this.stsSdv});

  String codEmp;
  dynamic clsSdv;
  String codVen;
  String numSdv;
  String fecSdv;
  String nunSdv;
  dynamic frmSdv;
  String codRef;
  String codPto;
  String codMov;
  String numMov;
  dynamic fecMov;
  dynamic frmMov;
  int secMov;
  String codPro;
  double canB91;
  double canB92;
  double canB93;
  double canB94;
  double canB95;
  double canB96;
  dynamic clsMdm;
  String codMdm;
  String obsMdm;
  String codMrm;
  String obsMrm;
  dynamic ofsSdv;
  String obsSdv;
  String codCop;
  String nomCop;
  String ngrCop;
  String fgrCop;
  double bltCop;
  String destino;
  String ptoRel;
  String codRel;
  String numRel;
  dynamic fecRel;
  String ptoNex;
  String codNex;
  String numNex;
  dynamic fecNex;
  dynamic swsSdv;
  dynamic ucrSdv;
  dynamic fcrSdv;
  dynamic uacSdv;
  dynamic facSdv;
  dynamic uapSdv;
  dynamic fapSdv;
  String stsSdv;

  factory Ig0063.fromJson(String str) => Ig0063.fromMap(json.decode(str));

  String toJson() => json.encode(toMap());

  factory Ig0063.fromMap(Map<String, dynamic> json) => Ig0063(
        codEmp: json["cod_emp"],
        clsSdv: json["cls_sdv"],
        codVen: json["cod_ven"],
        numSdv: json["num_sdv"],
        fecSdv: json["fec_sdv"],
        nunSdv: json["nun_sdv"],
        frmSdv: json["frm_sdv"],
        codRef: json["cod_ref"],
        codPto: json["cod_pto"],
        codMov: json["cod_mov"],
        numMov: json["num_mov"],
        fecMov: json["fec_mov"],
        frmMov: json["frm_mov"],
        secMov: json["sec_mov"],
        codPro: json["cod_pro"],
        canB91: json["can_b91"],
        canB92: json["can_b92"],
        canB93: json["can_b93"],
        canB94: json["can_b94"],
        canB95: json["can_b95"],
        canB96: json["can_b96"],
        clsMdm: json["cls_mdm"],
        codMdm: json["cod_mdm"],
        obsMdm: json["obs_mdm"],
        codMrm: json["cod_mrm"],
        obsMrm: json["obs_mrm"],
        ofsSdv: json["ofs_sdv"],
        obsSdv: json["obs_sdv"],
        codCop: json["cod_cop"],
        nomCop: json["nom_cop"],
        ngrCop: json["ngr_cop"],
        fgrCop: json["fgr_cop"],
        bltCop: json["blt_cop"].toDouble(),
        destino: json["destino"],
        ptoRel: json["pto_rel"],
        codRel: json["cod_rel"],
        numRel: json["num_rel"],
        fecRel: json["fec_rel"],
        ptoNex: json["pto_nex"],
        codNex: json["cod_nex"],
        numNex: json["num_nex"],
        fecNex: json["fec_nex"],
        swsSdv: json["sws_sdv"],
        ucrSdv: json["ucr_sdv"],
        fcrSdv: json["fcr_sdv"],
        uacSdv: json["uac_sdv"],
        facSdv: json["fac_sdv"],
        uapSdv: json["uap_sdv"],
        fapSdv: json["fap_sdv"],
        stsSdv: json["sts_sdv"],
      );

  Map<String, dynamic> toMap() => {
        "cod_emp": codEmp,
        "cls_sdv": clsSdv,
        "cod_ven": codVen,
        "num_sdv": numSdv,
        "fec_sdv": fecSdv,
        "nun_sdv": nunSdv,
        "frm_sdv": frmSdv,
        "cod_ref": codRef,
        "cod_pto": codPto,
        "cod_mov": codMov,
        "num_mov": numMov,
        "fec_mov": fecMov,
        "frm_mov": frmMov,
        "sec_mov": secMov,
        "cod_pro": codPro,
        "can_b91": canB91,
        "can_b92": canB92,
        "can_b93": canB93,
        "can_b94": canB94,
        "can_b95": canB95,
        "can_b96": canB96,
        "cls_mdm": clsMdm,
        "cod_mdm": codMdm,
        "obs_mdm": obsMdm,
        "cod_mrm": codMrm,
        "obs_mrm": obsMrm,
        "ofs_sdv": ofsSdv,
        "obs_sdv": obsSdv,
        "cod_cop": codCop,
        "nom_cop": nomCop,
        "ngr_cop": ngrCop,
        "fgr_cop": fgrCop,
        "blt_cop": bltCop,
        "destino": destino,
        "pto_rel": ptoRel,
        "cod_rel": codRel,
        "num_rel": numRel,
        "fec_rel": fecRel,
        "pto_nex": ptoNex,
        "cod_nex": codNex,
        "num_nex": numNex,
        "fec_nex": fecNex,
        "sws_sdv": swsSdv,
        "ucr_sdv": ucrSdv,
        "fcr_sdv": fcrSdv,
        "uac_sdv": uacSdv,
        "fac_sdv": facSdv,
        "uap_sdv": uapSdv,
        "fap_sdv": fapSdv,
        "sts_sdv": stsSdv,
      };
}
