import 'dart:convert';

class Ig0062 {
  Ig0062({
    required this.codEmp,
    required this.numSdv,
    required this.fecSdv,
    required this.nunSdv,
    required this.frmSdv,
    required this.codRef,
    required this.codVen,
    required this.codPto,
    required this.codMov,
    required this.numMov,
    required this.fecMov,
    required this.secMov,
    required this.codPro,
    required this.canSdv,
    required this.canMov,
    required this.clsMdm,
    required this.codMdm,
    required this.obsMdm,
    required this.kd1Mdm,
    required this.ofsSdv,
    required this.obsSdv,
    required this.codCop,
    required this.nomCop,
    required this.ngrCop,
    required this.fgrCop,
    required this.bltCop,
    required this.destino,
    required this.ptoRel,
    required this.codRel,
    required this.numRel,
    required this.fecRel,
    required this.ptoNex,
    required this.codNex,
    required this.numNex,
    required this.fecNex,
    required this.swsSdv,
    required this.urcSdv,
    required this.fcrSdv,
    required this.uacSdv,
    required this.facSdv,
    required this.uapSdv,
    required this.fapSdv,
    required this.stsSdv,
  });

  String codEmp;
  String numSdv;
  String fecSdv;
  String nunSdv;
  String frmSdv;
  String codRef;
  String codVen;
  String codPto;
  String codMov;
  String numMov;
  String fecMov;
  int secMov;
  String codPro;
  double canSdv;
  double canMov;
  String clsMdm;
  String codMdm;
  String obsMdm;
  String kd1Mdm;
  String ofsSdv;
  String obsSdv;
  String codCop;
  String nomCop;
  String ngrCop;
  String fgrCop;
  double bltCop;
  String destino;
  String ptoRel;
  String codRel;
  String numRel;
  String fecRel;
  String ptoNex;
  String codNex;
  String numNex;
  String fecNex;
  String swsSdv;
  String urcSdv;
  String fcrSdv;
  String uacSdv;
  String facSdv;
  String uapSdv;
  String fapSdv;
  String stsSdv;

  factory Ig0062.fromJson(String str) => Ig0062.fromMap(json.decode(str));

  String toJson() => json.encode(toMap());

  factory Ig0062.fromMap(Map<String, dynamic> json) => Ig0062(
        codEmp: json["cod_emp"],
        numSdv: json["num_sdv"],
        fecSdv: json["fec_sdv"],
        nunSdv: json["nun_sdv"],
        frmSdv: json["frm_sdv"],
        codRef: json["cod_ref"],
        codVen: json["cod_ven"],
        codPto: json["cod_pto"],
        codMov: json["cod_mov"],
        numMov: json["num_mov"],
        fecMov: json["fec_mov"],
        secMov: json["sec_mov"],
        codPro: json["cod_pro"],
        canSdv: json["can_sdv"],
        canMov: json["can_mov"],
        clsMdm: json["cls_mdm"],
        codMdm: json["cod_mdm"],
        obsMdm: json["obs_mdm"],
        kd1Mdm: json["kd1_mdm"],
        ofsSdv: json["ofs_sdv"],
        obsSdv: json["obs_sdv"],
        codCop: json["cod_cop"],
        nomCop: json["nom_cop"],
        ngrCop: json["ngr_cop"],
        fgrCop: json["fgr_cop"],
        bltCop: json["blt_cop"],
        destino: json["destino"],
        ptoRel: json["pto_rel"],
        codRel: json["cod_rel"],
        numRel: json["num_rel"],
        fecRel: json["fec_rel"],
        ptoNex: json["pto_nex"],
        codNex: json["cod_nex"],
        numNex: json["num_nex"],
        fecNex: json["fec_nex"],
        swsSdv: json["sws_sdv"],
        urcSdv: json["urc_sdv"],
        fcrSdv: json["fcr_sdv"],
        uacSdv: json["uac_sdv"],
        facSdv: json["fac_sdv"],
        uapSdv: json["uap_sdv"],
        fapSdv: json["fap_sdv"],
        stsSdv: json["sts_sdv"],
      );

  Map<String, dynamic> toMap() => {
        "cod_emp": codEmp,
        "num_sdv": numSdv,
        "fec_sdv": fecSdv,
        "nun_sdv": nunSdv,
        "frm_sdv": frmSdv,
        "cod_ref": codRef,
        "cod_ven": codVen,
        "cod_pto": codPto,
        "cod_mov": codMov,
        "num_mov": numMov,
        "fec_mov": fecMov,
        "sec_mov": secMov,
        "cod_pro": codPro,
        "can_sdv": canSdv,
        "can_mov": canMov,
        "cls_mdm": clsMdm,
        "cod_mdm": codMdm,
        "obs_mdm": obsMdm,
        "kd1_mdm": kd1Mdm,
        "ofs_sdv": ofsSdv,
        "obs_sdv": obsSdv,
        "cod_cop": codCop,
        "nom_cop": nomCop,
        "ngr_cop": ngrCop,
        "fgr_cop": fgrCop,
        "blt_cop": bltCop,
        "destino": destino,
        "pto_rel": ptoRel,
        "cod_rel": codRel,
        "num_rel": numRel,
        "fec_rel": fecRel,
        "pto_nex": ptoNex,
        "cod_nex": codNex,
        "num_nex": numNex,
        "fec_nex": fecNex,
        "sws_sdv": swsSdv,
        "urc_sdv": urcSdv,
        "fcr_sdv": fcrSdv,
        "uac_sdv": uacSdv,
        "fac_sdv": facSdv,
        "uap_sdv": uapSdv,
        "fap_sdv": fapSdv,
        "sts_sdv": stsSdv,
      };
}
